export const MENU_ITEMS = [
  {
    title: 'Greek Salad',
    description: 'Freshly cut tomatoes, cucumbers, onions, olives, and feta cheese.',
    price: 12.99,
    categories: ['Starters', 'Mains'],
    ingredients: ['tomatoes', 'cucumbers', 'onions', 'olives', 'feta cheese', 'signature dressing', 'peri-peri seasoning', 'salt', 'pepper'],
    img: require('../../assets/menu-items/greek-salad.avif'),
  },
  {
    title: 'Ceasar Salad',
    description: 'Freshly cut romaine lettuce, croutons, and parmesan cheese.',
    price: 10.99,
    categories: ['Starters', 'Mains'],
    ingredients: ['romaine lettuce', 'croutons', 'parmesan cheese'],
    img: require('../../assets/menu-items/greek-salad.avif'),
  },
  {
    title: 'Chicken Wings',
    description: 'Freshly fried chicken wings with your choice of sauce.',
    price: 8.99,
    categories: ['Starters'],
    ingredients: ['chicken wings', 'signature sauce'],
    img: require('../../assets/menu-items/greek-salad.avif'),
  },
  {
    title: 'Chicken Tenders',
    description: 'Freshly fried chicken tenders with your choice of sauce.',
    price: 8.99,
    categories: ['Starters'],
    ingredients: ['chicken tenders', 'signature sauce'],
    img: require('../../assets/menu-items/greek-salad.avif'),
  },
  {
    title: 'Chicken Sandwich',
    description: 'Freshly grilled chicken breast with lettuce, tomato, and onion.',
    price: 12.99,
    categories: ['Mains'],
    ingredients: ['chicken breast', 'lettuce', 'tomato', 'onion'],
    img: require('../../assets/menu-items/greek-salad.avif'),
  },
  {
    title: 'Cheeseburger',
    description: 'Freshly grilled beef patty with lettuce, tomato, and onion.',
    price: 12.99,
    categories: ['Mains'],
    ingredients: ['beef patty', 'lettuce', 'tomato', 'onion'],
    img: require('../../assets/menu-items/greek-salad.avif'),
  },
  {
    title: 'Pizza',
    description: 'Freshly baked pizza with your choice of toppings.',
    price: 12.99,
    categories: ['Mains'],
    ingredients: ['pizza dough', 'signature sauce', 'cheese', 'toppings'],
    img: require('../../assets/menu-items/greek-salad.avif'),
  },
  {
    title: 'Spaghetti',
    description: 'Freshly cooked spaghetti with your choice of sauce.',
    price: 10.99,
    categories: ['Mains'],
    ingredients: ['spaghetti', 'signature sauce'],
    img: require('../../assets/menu-items/greek-salad.avif'),
  },
  {
    title: 'Hot Lava Cake',
    description: 'Freshly baked chocolate cake with a warm chocolate center.',
    price: 6.99,
    categories: ['Desserts'],
    ingredients: ['chocolate cake', 'cocao powder', 'chocolate frosting'],
    img: require('../../assets/menu-items/greek-salad.avif'),
  },
  {
    title: 'Mochi Ice Cream',
    description: 'Freshly made mochi ice cream with your choice of flavor.',
    price: 6.99,
    categories: ['Desserts'],
    ingredients: ['home-made mochi', 'vanilla ice cream', 'bean jam paste'],
    img: require('../../assets/menu-items/greek-salad.avif'),
  },
  {
    title: 'Virgin Pina Colada',
    description: 'Freshly blended pineapple and coconut juice.',
    price: 4.99,
    categories: ['Drinks'],
    ingredients: ['pineapple juice', 'coconut juice'],
    img: require('../../assets/menu-items/greek-salad.avif'),
  },
  {
    title: 'Virgin Strawberry Daiquiri',
    description: 'Freshly blended strawberries and lime juice.',
    price: 4.99,
    categories: ['Drinks'],
    ingredients: ['strawberries', 'lime juice'],
    img: require('../../assets/menu-items/greek-salad.avif'),
  },
  {
    title: 'French Fries',
    description: 'Freshly fried french fries.',
    price: 2.99,
    categories: ['Sides'],
    ingredients: ['potatoes', 'signature seasoning'],
    img: require('../../assets/menu-items/greek-salad.avif'),
  },
  {
    title: 'Onion Rings',
    description: 'Freshly fried onion rings.',
    price: 2.99,
    categories: ['Sides'],
    ingredients: ['onions', 'signature seasoning'],
    img: require('../../assets/menu-items/greek-salad.avif'),
  },
  {
    title: 'Soup of the Day',
    description: 'Freshly made soup.',
    price: 4.99,
    categories: ['Specials'],
    ingredients: ['shhh... it\'s a secret'],
    img: require('../../assets/menu-items/greek-salad.avif'),
  },
  {
    title: 'Chef\'s Special',
    description: 'Ask your server about today\'s special.',
    price: 14.99,
    categories: ['Specials'],
    ingredients: ['shhh... it\'s a secret'],
    img: require('../../assets/menu-items/greek-salad.avif'),
  },
];
